version: "3"

services:
  db:
    image: postgres:15
    ports:
      - "${TOKENGRAM_INDEXER_DB_HOST_PORT:-9010}:${DB_PORT:-5432}"
    env_file:
      - .env
    volumes:
      - "../pg-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d squid -U postgres"]
      interval: 5s
      timeout: 30s
      retries: 5
    networks:
      - team07
  api:
    image: indexer
    ports:
      # GraphQL endpoint at port 4350
      - "${TOKENGRAM_INDEXER_API_HOST_PORT:-9000}:4350"
    env_file:
      - .env
    command: ["sqd", "serve:prod"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - team07
  processor:
    image: indexer
    ports:
      - "${TOKENGRAM_INDEXER_PROCESSOR_HOST_PORT:-9001}:3000"
    env_file:
      - .env
    command: ["sqd", "process:prod"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - team07


networks:
  team07:
    name: team07
    external: true
